"""del email from token blacklist

Revision ID: 6cd0493050ea
Revises: 1cef69660040
Create Date: 2024-08-26 18:15:30.001377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6cd0493050ea'
down_revision: Union[str, None] = '1cef69660040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_token_blacklist_email', table_name='token_blacklist')
    op.drop_column('token_blacklist', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_blacklist', sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False))
    op.create_index('ix_token_blacklist_email', 'token_blacklist', ['email'], unique=True)
    # ### end Alembic commands ###
